# @package model
name: "AE"
args:
  sources: ${global.sources}
  architecture: ${architecture.name}
  architecture_params: ${architecture.args}
  pretrained_checkpoint: ${global.pretrained_checkpoint}