# @package model
name: "Supervised"
args:
  dim_l: ${global.dim_l}
  sources: ${global.sources}
  num_classes: ???
  architecture: ${architecture.name}
  architecture_params: ${architecture.args}
  pretrained_checkpoint: ${global.pretrained_checkpoint}