# @package criterion
name: SpatialMultiDim
args:
  dim_cls: ${global.dim_cls}
  estimator_setting:
    class_type: InfoNceEstimator
    args:
      critic_setting:
        class_type: SeparableCritic
        args:
      clip_setting:
        class_type: TahnClip
        args:
      penalty_setting:
        class_type: L2Penalty
        args:
  modes: [XX]
  weights: [1.]