hydra:
  job:
    name: ${global.name}
  run:
    dir: ${global.logdir}
global:
  name: ${model.name}
  dim_in: [1]
  dim_l: 64
  dim_cls: [8]
  dataset_dir: "../../../../data/"
  batch_size: 64
  input_dim: 2
  sources: [0]
  fold: 0
  num_folds: 5
  seed: 343
  num_workers: 0
  logdir: ./out/${global.name}/${global.fold}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  pretrained_checkpoint:
defaults:
  - dataset: two_view_mnist
  - architecture: dcgan_encoder
  - model: dim
  - criterion: spatial_multi_dim
  - task: pretraining
  - optimizer: radam
  - scheduler: one_cycle_lr
  - runner: catalyst_runner





