hydra:
  job:
    name: ${global.name}
  run:
    dir: ${global.logdir}
global:
  name: 'Supervised_v0'
  dim_in: [1]
  dim_l: 64
  dim_cls: []
  dataset_dir: "../../../../data"
  batch_size: 64
  views: [0]
  fold: 0
  num_folds: 5
  seed: 343
  num_workers: 0
  logdir: ./out/${global.name}/${now:%Y-%m-%d}/
  pretrained_checkpoint: None
defaults:
  - dataset: mnist_svhn
  - architecture: dcgan_encoder
  - model: supervised
  - criterion: ce
  - task: pretraining
  - optimizer: radam
  - scheduler: one_cycle_lr
  - runner: mnist_svhn_runner





