hydra:
    run:
        dir: ./out/${experiment.model.name}_/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: ./out/${experiment.model.name}_/multiruns/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
defaults:
  - experiment: mnist_svhn


