name: default
hydra:
    run:
        dir: ./out/${name}/${experiment.fold}/${experiment.task.name}/
    sweep:
        dir: ./out/${name}/${experiment.fold}/${experiment.task.name}/
        subdir: ${hydra.job.num}
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
defaults:
  - experiment: two_view_mnist_pretraining