# @package dataset
name: MnistSvhn
input_size: 32
data_type: "2D"
args:
  dataset_dir: ${global.dataset_dir}
  fold: ${global.fold}
  num_folds: ${global.num_folds}
  sources: ${global.sources}
  batch_size: ${global.batch_size}
  shuffle: ${task.shuffle}
  drop_last: ${task.drop_last}
  num_workers: ${global.num_workers}
  seed: ${global.seed}